### PR TITLE
Add new scripts to simplify install and development

### PR DESCRIPTION
**Pull request by SethBurkart123**
I added scripts that should work with all of the below:

- Windows (not tested)
- Macos
- Linux (various distributions - not tested)

If you find any problems then feel free to improve the scripts.

### CODE REVIEW

**Comment by SethBurkart123** [comment]
I fixed the windows script, Just about to dev linux... who knows what went on there.

**Comment by SethBurkart123** [comment]
All fixed, linux is now using [nvm](https://github.com/nvm-sh/nvm) to install everything and I just tested it all the scripts on MacOS, Windows 10 and Ubuntu 22.04

**Comment by MEGA-Dawg68** [comment]
It's alright, I just need to either reinstall Pop!_OS or fix couple hundred packages lol.

**Comment by SethBurkart123** [comment]
Couldn't you remove the volume and reinstall it the same way that you installed popos originally? Either that or delete the main volume, you might have to do that from a liveusb though

**Comment by MEGA-Dawg68** [comment]
Then my UEFI freaks out and I can't boot to windows, I have tried before. Also the windows install scripts still don't work 😅

**Comment by SethBurkart123** [comment]
> Then my UEFI freaks out and I can't boot to windows, I have tried before. Also the windows install scripts still don't work 😅

hmm, it was working for me on windows... are you able to send over the error?

**Comment by MEGA-Dawg68** [comment]
Yes, no build folder gets created

**Comment by SethBurkart123** [comment]
Yeah, Ok - it looks like there is an issue with one of the sections of the install script. It has got pnpm installed but it doesn't seem to be doing much with the packages... That'd explain why the dev script isn't working.

**Pull request merged**
